### ISSUE TITLE
Comment shortcut not using correct comment syntax

### ISSUE THREAD

**Issue by michaeloliverx** [mdx-js/vscode-mdx#203]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdxv2

### Steps to reproduce

Inside VSCode open a `.mdx` file and hightlight a line e.g.
```mdx
# Some cool heading
```

Press <kbd>CMD</kbd> + <kbd>/</kbd> on macOS or <kbd>Ctrl</kbd> + <kbd>/</kbd>. Observe the line changes to:
```mdx
<!-- # Some cool heading -->
```

### Expected behavior

MDX requires using JS comment syntax not HTML e.g.
```mdx
{/* # Some cool heading */}
```

### Actual behavior

Wrong syntax is used.

### Runtime

Node v16

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

webpack, Next.js

**Comment by michaeloliverx** [comment]
The latest version on the marketplace is `v0.3.2` but on here its `v1.0.0` so it looks like the latest changes aren't live yet.

**Comment by grahampcharles** [comment]
The marketplace has been bumped to v1.0.1 and I am experiencing the same issue.

**Comment by grahampcharles** [comment]
I have been experimenting for a while now and discovered that if you remove `contributes.grammars` from `package.json`, the commenting works as expected. This surprised me, since I thought `grammars` were the textmate rule for syntax *highlighting* and nothing more. But, anyway, it shows where the problem lies.

**Comment by grahampcharles** [comment]
Found it. The setting `contributes.grammars.embeddedLanguages` includes the directive 

`          "text.html.markdown": "markdown", `

This shouldn't be there, I think. MDX files won't have *embedded* markdown -- that part of the grammar definition, I think, is for CSS within HTML and stuff like that. If markdown (non-MDX markdown) is indicated as an *embedded* language, then it will take over and overrule MDX commenting and so on.

Anyway, if you remove that line from `grammars.embeddedLanguages` then MDX2 commenting works as expected *and* normal markdown syntax highlighting does, as well.

I'm going to read the contribution guide and submit a PR. I don't do this very often, please be gentle!

**Comment by JounQin** [comment]
> MDX files won't have embedded markdown

@grahampcharles Sorry for the delay first, but I'm not quite sure to understand this. Why markdown can not be included in MDX?

**Comment by grahampcharles** [comment]
Well, because MDX is itself a *version* of markdown. If you indicate that markdown can be included as an embed *within* markdown, then your markdown language configuration will take over. 

The embedded grammar is there for including *other* grammars within your parent language configuration. For example, if you have `<style>` tags within HTML, you want CSS language features to take over. In MDX, though, you *don't* want markdown language features, you want MDX language features. 

The proof is in the pudding, though. If you remove the embed line, then MDX commenting works correctly. If you leave it in, then it does not -- the markdown language configuration takes over.

**Comment by JounQin** [comment]
@grahampcharles Thanks.

I just forgot `mdx@v2` doesn't use HTML style comments anymore.

**Comment by michaeloliverx** [comment]
I can confirm that the latest version `v1.0.3` uses the correct syntax now when using the comment shortcut for embedded markdown:
```jsx
{/* ## Headings */}
```

__but__ it doesn't work on ESM import/exports or embedded JavaScript:
```jsx
// export const foo = "bar";
```

**Comment by JounQin** [comment]
`export const foo = "bar";` is recognized as `ES module syntax`, so its comments are `//` by default. It needs some kind of investigation.

cc @remcohaszing

Do you have any experience about this?

**Comment by JounQin** [comment]
close in favor of #221
